default:
  golem_name: idrFluent
  golem_version: 0.0.0.9000
  app_prod: no
  AWS_IDR_PASSWORD: !expr Sys.getenv("AWS_IDR_PASSWORD")
  AWS_ACCESS_KEY_ID: !expr Sys.getenv("AWS_ACCESS_KEY_ID")
  AWS_SECRET_ACCESS_KEY: !expr Sys.getenv("AWS_SECRET_ACCESS_KEY")
  AWS_DEFAULT_REGION: !expr Sys.getenv("AWS_DEFAULT_REGION")
production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
rsconnect:
  AWS_IDR_PASSWORD: !expr Sys.getenv("AWS_IDR_PASSWORD")
  AWS_ACCESS_KEY_ID: !expr Sys.getenv("AWS_ACCESS_KEY_ID")
  AWS_SECRET_ACCESS_KEY: !expr Sys.getenv("AWS_SECRET_ACCESS_KEY")
  AWS_DEFAULT_REGION: !expr Sys.getenv("AWS_DEFAULT_REGION")
