default:
  golem_name: idrFluent
  golem_version: 0.0.0.9000
  app_prod: no
  AWS_IDR_PASSWORD: !expr Sys.getenv("AWS_IDR_PASSWORD")
production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
rsconnect:
  AWS_IDR_PASSWORD: !expr Sys.getenv("AWS_IDR_PASSWORD")
